// Generated by gencpp from file ros_exercises/check_palindromeResponse.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_CHECK_PALINDROMERESPONSE_H
#define ROS_EXERCISES_MESSAGE_CHECK_PALINDROMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_exercises
{
template <class ContainerAllocator>
struct check_palindromeResponse_
{
  typedef check_palindromeResponse_<ContainerAllocator> Type;

  check_palindromeResponse_()
    : bit(0)  {
    }
  check_palindromeResponse_(const ContainerAllocator& _alloc)
    : bit(0)  {
  (void)_alloc;
    }



   typedef int8_t _bit_type;
  _bit_type bit;





  typedef boost::shared_ptr< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct check_palindromeResponse_

typedef ::ros_exercises::check_palindromeResponse_<std::allocator<void> > check_palindromeResponse;

typedef boost::shared_ptr< ::ros_exercises::check_palindromeResponse > check_palindromeResponsePtr;
typedef boost::shared_ptr< ::ros_exercises::check_palindromeResponse const> check_palindromeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_exercises::check_palindromeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_exercises::check_palindromeResponse_<ContainerAllocator1> & lhs, const ::ros_exercises::check_palindromeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.bit == rhs.bit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_exercises::check_palindromeResponse_<ContainerAllocator1> & lhs, const ::ros_exercises::check_palindromeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_exercises

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ef3392b71b4bc9968c0cbe6d4880901";
  }

  static const char* value(const ::ros_exercises::check_palindromeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ef3392b71b4bc99ULL;
  static const uint64_t static_value2 = 0x68c0cbe6d4880901ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_exercises/check_palindromeResponse";
  }

  static const char* value(const ::ros_exercises::check_palindromeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 bit\n"
"\n"
;
  }

  static const char* value(const ::ros_exercises::check_palindromeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct check_palindromeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_exercises::check_palindromeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_exercises::check_palindromeResponse_<ContainerAllocator>& v)
  {
    s << indent << "bit: ";
    Printer<int8_t>::stream(s, indent + "  ", v.bit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_CHECK_PALINDROMERESPONSE_H
