// Generated by gencpp from file ros_exercises/check_palindrome.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_CHECK_PALINDROME_H
#define ROS_EXERCISES_MESSAGE_CHECK_PALINDROME_H

#include <ros/service_traits.h>


#include <ros_exercises/check_palindromeRequest.h>
#include <ros_exercises/check_palindromeResponse.h>


namespace ros_exercises
{

struct check_palindrome
{

typedef check_palindromeRequest Request;
typedef check_palindromeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct check_palindrome
} // namespace ros_exercises


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_exercises::check_palindrome > {
  static const char* value()
  {
    return "9435240a40d8ae413a3b7925d764bbcf";
  }

  static const char* value(const ::ros_exercises::check_palindrome&) { return value(); }
};

template<>
struct DataType< ::ros_exercises::check_palindrome > {
  static const char* value()
  {
    return "ros_exercises/check_palindrome";
  }

  static const char* value(const ::ros_exercises::check_palindrome&) { return value(); }
};


// service_traits::MD5Sum< ::ros_exercises::check_palindromeRequest> should match
// service_traits::MD5Sum< ::ros_exercises::check_palindrome >
template<>
struct MD5Sum< ::ros_exercises::check_palindromeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_exercises::check_palindrome >::value();
  }
  static const char* value(const ::ros_exercises::check_palindromeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_exercises::check_palindromeRequest> should match
// service_traits::DataType< ::ros_exercises::check_palindrome >
template<>
struct DataType< ::ros_exercises::check_palindromeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_exercises::check_palindrome >::value();
  }
  static const char* value(const ::ros_exercises::check_palindromeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_exercises::check_palindromeResponse> should match
// service_traits::MD5Sum< ::ros_exercises::check_palindrome >
template<>
struct MD5Sum< ::ros_exercises::check_palindromeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_exercises::check_palindrome >::value();
  }
  static const char* value(const ::ros_exercises::check_palindromeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_exercises::check_palindromeResponse> should match
// service_traits::DataType< ::ros_exercises::check_palindrome >
template<>
struct DataType< ::ros_exercises::check_palindromeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_exercises::check_palindrome >::value();
  }
  static const char* value(const ::ros_exercises::check_palindromeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_CHECK_PALINDROME_H
