// Generated by gencpp from file ros_exercises/check_palindromeRequest.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_CHECK_PALINDROMEREQUEST_H
#define ROS_EXERCISES_MESSAGE_CHECK_PALINDROMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_exercises
{
template <class ContainerAllocator>
struct check_palindromeRequest_
{
  typedef check_palindromeRequest_<ContainerAllocator> Type;

  check_palindromeRequest_()
    : input()  {
    }
  check_palindromeRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct check_palindromeRequest_

typedef ::ros_exercises::check_palindromeRequest_<std::allocator<void> > check_palindromeRequest;

typedef boost::shared_ptr< ::ros_exercises::check_palindromeRequest > check_palindromeRequestPtr;
typedef boost::shared_ptr< ::ros_exercises::check_palindromeRequest const> check_palindromeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_exercises::check_palindromeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_exercises::check_palindromeRequest_<ContainerAllocator1> & lhs, const ::ros_exercises::check_palindromeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_exercises::check_palindromeRequest_<ContainerAllocator1> & lhs, const ::ros_exercises::check_palindromeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_exercises

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39e92f1778057359c64c7b8a7d7b19de";
  }

  static const char* value(const ::ros_exercises::check_palindromeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39e92f1778057359ULL;
  static const uint64_t static_value2 = 0xc64c7b8a7d7b19deULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_exercises/check_palindromeRequest";
  }

  static const char* value(const ::ros_exercises::check_palindromeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input\n"
;
  }

  static const char* value(const ::ros_exercises::check_palindromeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct check_palindromeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_exercises::check_palindromeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_exercises::check_palindromeRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_CHECK_PALINDROMEREQUEST_H
