// Generated by gencpp from file ros_exercises/compute_statisticsRequest.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_COMPUTE_STATISTICSREQUEST_H
#define ROS_EXERCISES_MESSAGE_COMPUTE_STATISTICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_exercises
{
template <class ContainerAllocator>
struct compute_statisticsRequest_
{
  typedef compute_statisticsRequest_<ContainerAllocator> Type;

  compute_statisticsRequest_()
    : input()  {
    }
  compute_statisticsRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct compute_statisticsRequest_

typedef ::ros_exercises::compute_statisticsRequest_<std::allocator<void> > compute_statisticsRequest;

typedef boost::shared_ptr< ::ros_exercises::compute_statisticsRequest > compute_statisticsRequestPtr;
typedef boost::shared_ptr< ::ros_exercises::compute_statisticsRequest const> compute_statisticsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator1> & lhs, const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator1> & lhs, const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_exercises

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67001d40e8c46d0f13fef73f0cd86f54";
  }

  static const char* value(const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67001d40e8c46d0fULL;
  static const uint64_t static_value2 = 0x13fef73f0cd86f54ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_exercises/compute_statisticsRequest";
  }

  static const char* value(const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] input\n"
;
  }

  static const char* value(const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct compute_statisticsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_exercises::compute_statisticsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_exercises::compute_statisticsRequest_<ContainerAllocator>& v)
  {
    s << indent << "input[]" << std::endl;
    for (size_t i = 0; i < v.input.size(); ++i)
    {
      s << indent << "  input[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.input[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_COMPUTE_STATISTICSREQUEST_H
