// Generated by gencpp from file ros_exercises/compute_statisticsResponse.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_COMPUTE_STATISTICSRESPONSE_H
#define ROS_EXERCISES_MESSAGE_COMPUTE_STATISTICSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_exercises
{
template <class ContainerAllocator>
struct compute_statisticsResponse_
{
  typedef compute_statisticsResponse_<ContainerAllocator> Type;

  compute_statisticsResponse_()
    : median(0.0)
    , mode(0.0)
    , mean(0.0)  {
    }
  compute_statisticsResponse_(const ContainerAllocator& _alloc)
    : median(0.0)
    , mode(0.0)
    , mean(0.0)  {
  (void)_alloc;
    }



   typedef float _median_type;
  _median_type median;

   typedef float _mode_type;
  _mode_type mode;

   typedef float _mean_type;
  _mean_type mean;





  typedef boost::shared_ptr< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct compute_statisticsResponse_

typedef ::ros_exercises::compute_statisticsResponse_<std::allocator<void> > compute_statisticsResponse;

typedef boost::shared_ptr< ::ros_exercises::compute_statisticsResponse > compute_statisticsResponsePtr;
typedef boost::shared_ptr< ::ros_exercises::compute_statisticsResponse const> compute_statisticsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator1> & lhs, const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.median == rhs.median &&
    lhs.mode == rhs.mode &&
    lhs.mean == rhs.mean;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator1> & lhs, const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_exercises

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e77fe3e8f7ae7330fc10b10697279a21";
  }

  static const char* value(const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe77fe3e8f7ae7330ULL;
  static const uint64_t static_value2 = 0xfc10b10697279a21ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_exercises/compute_statisticsResponse";
  }

  static const char* value(const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 median\n"
"float32 mode\n"
"float32 mean\n"
"\n"
;
  }

  static const char* value(const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.median);
      stream.next(m.mode);
      stream.next(m.mean);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct compute_statisticsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_exercises::compute_statisticsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_exercises::compute_statisticsResponse_<ContainerAllocator>& v)
  {
    s << indent << "median: ";
    Printer<float>::stream(s, indent + "  ", v.median);
    s << indent << "mode: ";
    Printer<float>::stream(s, indent + "  ", v.mode);
    s << indent << "mean: ";
    Printer<float>::stream(s, indent + "  ", v.mean);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_COMPUTE_STATISTICSRESPONSE_H
