// Generated by gencpp from file ros_exercises/find_min_arrayRequest.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAYREQUEST_H
#define ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_exercises
{
template <class ContainerAllocator>
struct find_min_arrayRequest_
{
  typedef find_min_arrayRequest_<ContainerAllocator> Type;

  find_min_arrayRequest_()
    : array()  {
    }
  find_min_arrayRequest_(const ContainerAllocator& _alloc)
    : array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _array_type;
  _array_type array;





  typedef boost::shared_ptr< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct find_min_arrayRequest_

typedef ::ros_exercises::find_min_arrayRequest_<std::allocator<void> > find_min_arrayRequest;

typedef boost::shared_ptr< ::ros_exercises::find_min_arrayRequest > find_min_arrayRequestPtr;
typedef boost::shared_ptr< ::ros_exercises::find_min_arrayRequest const> find_min_arrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator1> & lhs, const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.array == rhs.array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator1> & lhs, const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_exercises

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71f1005c81b671681646a574c6360c24";
  }

  static const char* value(const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71f1005c81b67168ULL;
  static const uint64_t static_value2 = 0x1646a574c6360c24ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_exercises/find_min_arrayRequest";
  }

  static const char* value(const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] array\n"
;
  }

  static const char* value(const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct find_min_arrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_exercises::find_min_arrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_exercises::find_min_arrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "array[]" << std::endl;
    for (size_t i = 0; i < v.array.size(); ++i)
    {
      s << indent << "  array[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAYREQUEST_H
