// Generated by gencpp from file ros_exercises/find_min_array.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAY_H
#define ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAY_H

#include <ros/service_traits.h>


#include <ros_exercises/find_min_arrayRequest.h>
#include <ros_exercises/find_min_arrayResponse.h>


namespace ros_exercises
{

struct find_min_array
{

typedef find_min_arrayRequest Request;
typedef find_min_arrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct find_min_array
} // namespace ros_exercises


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_exercises::find_min_array > {
  static const char* value()
  {
    return "c14a13c8d67ff0e22069dfcdf7c3d804";
  }

  static const char* value(const ::ros_exercises::find_min_array&) { return value(); }
};

template<>
struct DataType< ::ros_exercises::find_min_array > {
  static const char* value()
  {
    return "ros_exercises/find_min_array";
  }

  static const char* value(const ::ros_exercises::find_min_array&) { return value(); }
};


// service_traits::MD5Sum< ::ros_exercises::find_min_arrayRequest> should match
// service_traits::MD5Sum< ::ros_exercises::find_min_array >
template<>
struct MD5Sum< ::ros_exercises::find_min_arrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_exercises::find_min_array >::value();
  }
  static const char* value(const ::ros_exercises::find_min_arrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_exercises::find_min_arrayRequest> should match
// service_traits::DataType< ::ros_exercises::find_min_array >
template<>
struct DataType< ::ros_exercises::find_min_arrayRequest>
{
  static const char* value()
  {
    return DataType< ::ros_exercises::find_min_array >::value();
  }
  static const char* value(const ::ros_exercises::find_min_arrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_exercises::find_min_arrayResponse> should match
// service_traits::MD5Sum< ::ros_exercises::find_min_array >
template<>
struct MD5Sum< ::ros_exercises::find_min_arrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_exercises::find_min_array >::value();
  }
  static const char* value(const ::ros_exercises::find_min_arrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_exercises::find_min_arrayResponse> should match
// service_traits::DataType< ::ros_exercises::find_min_array >
template<>
struct DataType< ::ros_exercises::find_min_arrayResponse>
{
  static const char* value()
  {
    return DataType< ::ros_exercises::find_min_array >::value();
  }
  static const char* value(const ::ros_exercises::find_min_arrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAY_H
