// Generated by gencpp from file ros_exercises/find_min_arrayResponse.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAYRESPONSE_H
#define ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_exercises
{
template <class ContainerAllocator>
struct find_min_arrayResponse_
{
  typedef find_min_arrayResponse_<ContainerAllocator> Type;

  find_min_arrayResponse_()
    : min(0.0)  {
    }
  find_min_arrayResponse_(const ContainerAllocator& _alloc)
    : min(0.0)  {
  (void)_alloc;
    }



   typedef float _min_type;
  _min_type min;





  typedef boost::shared_ptr< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct find_min_arrayResponse_

typedef ::ros_exercises::find_min_arrayResponse_<std::allocator<void> > find_min_arrayResponse;

typedef boost::shared_ptr< ::ros_exercises::find_min_arrayResponse > find_min_arrayResponsePtr;
typedef boost::shared_ptr< ::ros_exercises::find_min_arrayResponse const> find_min_arrayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator1> & lhs, const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator2> & rhs)
{
  return lhs.min == rhs.min;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator1> & lhs, const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_exercises

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bb7e81bbecf53f22e90b5a424f4cb01";
  }

  static const char* value(const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bb7e81bbecf53f2ULL;
  static const uint64_t static_value2 = 0x2e90b5a424f4cb01ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_exercises/find_min_arrayResponse";
  }

  static const char* value(const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 min\n"
"\n"
;
  }

  static const char* value(const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct find_min_arrayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_exercises::find_min_arrayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_exercises::find_min_arrayResponse_<ContainerAllocator>& v)
  {
    s << indent << "min: ";
    Printer<float>::stream(s, indent + "  ", v.min);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_FIND_MIN_ARRAYRESPONSE_H
