// Generated by gencpp from file ros_exercises/primes_list.msg
// DO NOT EDIT!


#ifndef ROS_EXERCISES_MESSAGE_PRIMES_LIST_H
#define ROS_EXERCISES_MESSAGE_PRIMES_LIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_exercises
{
template <class ContainerAllocator>
struct primes_list_
{
  typedef primes_list_<ContainerAllocator> Type;

  primes_list_()
    : data()  {
    }
  primes_list_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros_exercises::primes_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_exercises::primes_list_<ContainerAllocator> const> ConstPtr;

}; // struct primes_list_

typedef ::ros_exercises::primes_list_<std::allocator<void> > primes_list;

typedef boost::shared_ptr< ::ros_exercises::primes_list > primes_listPtr;
typedef boost::shared_ptr< ::ros_exercises::primes_list const> primes_listConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_exercises::primes_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_exercises::primes_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_exercises::primes_list_<ContainerAllocator1> & lhs, const ::ros_exercises::primes_list_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_exercises::primes_list_<ContainerAllocator1> & lhs, const ::ros_exercises::primes_list_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_exercises

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::primes_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_exercises::primes_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::primes_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_exercises::primes_list_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::primes_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_exercises::primes_list_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_exercises::primes_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "715b81068192546a86f8c2db120d2a3c";
  }

  static const char* value(const ::ros_exercises::primes_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x715b81068192546aULL;
  static const uint64_t static_value2 = 0x86f8c2db120d2a3cULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_exercises::primes_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_exercises/primes_list";
  }

  static const char* value(const ::ros_exercises::primes_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_exercises::primes_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64[] data\n"
;
  }

  static const char* value(const ::ros_exercises::primes_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_exercises::primes_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct primes_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_exercises::primes_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_exercises::primes_list_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_EXERCISES_MESSAGE_PRIMES_LIST_H
