(cl:defpackage ros_exercises-srv
  (:use )
  (:export
   "CHECK_PALINDROME"
   "<CHECK_PALINDROME-REQUEST>"
   "CHECK_PALINDROME-REQUEST"
   "<CHECK_PALINDROME-RESPONSE>"
   "CHECK_PALINDROME-RESPONSE"
   "COMPUTE_STATISTICS"
   "<COMPUTE_STATISTICS-REQUEST>"
   "COMPUTE_STATISTICS-REQUEST"
   "<COMPUTE_STATISTICS-RESPONSE>"
   "COMPUTE_STATISTICS-RESPONSE"
   "FIND_MIN_ARRAY"
   "<FIND_MIN_ARRAY-REQUEST>"
   "FIND_MIN_ARRAY-REQUEST"
   "<FIND_MIN_ARRAY-RESPONSE>"
   "FIND_MIN_ARRAY-RESPONSE"
  ))

